### PR TITLE
Fix invalid bulk syncs

### PR DESCRIPTION
**Pull request by ghmeier**
Without this check, it's possible to infinitely loop on completley
failed queries (i.e. invalid syntax). This adds a check for completely
failed queries and emits an error in response.

This is based on this PR https://github.com/bigpictureio/jsforce/pull/2 from bigpictureio (they gave us some details here: https://mail.mixmax.com/m/XJ6r8D7EfjyWxl57f)

### CODE REVIEW

**Comment by ghmeier** [comment]
fyi, @ttacon here's one of the fixes mentioned in the [email thread](https://mail.mixmax.com/m/lgaxjtxvO8t18O2OX), just have to fix up the tests.

**Comment by bradvogel** [comment]
@ghmeier can this be closed or merged?

**Comment by bradvogel** [comment]
@ghmeier merge or close?

**Comment by bradvogel** [comment]
Closing due to age. Feel free to reopen.

**Pull request closed without merging**
