### PR TITLE
V1.8.5

### PR DESCRIPTION
**Pull request by david0673**
I'm not sure why the build is failing, seemingly for the same reasons all the other PRs are failing.
All i'm really doing here is merging `jsforce:master` into `mixmaxhq:master`.

I've only tested by running a `conn.bulk.load` with PKChunking options, seemed to work fine.
Let me know what else i can do to help out in getting this merged.

### CODE REVIEW

**Comment by mericsson** [comment]
Hey @david0673 thanks for this. Are you using this mixmax fork for the bulk connection fixes/improvements?

fwiw we hope to merge it back into `jsforce:master` at some point.

Likely this is failing due to our travis set up. Have you run the tests locally and they pass?

**Comment by david0673** [comment]
I was planning on it, though i found the pk-chunking support to be flawed; failing often on long operations.
I wrote a fix for this & i intend to submit a PR to jsforce directly but i promise i will share the link with you & give credit where it is due :)

I did not run the tests locally

**Comment by mericsson** [comment]
@david0673 Ooh would love to see a preview of what that fix looks like if you can share.

**Comment by david0673** [comment]
Believe me @mericsson, I would love to share it as well! 😄 
I want to clean it up a bit first though, i'll try to get it done ASAP.
If i can't get it done during the week (busy busy busy), i will definitely get to it over the weekend, so worst case, within a week!

**Comment by david0673** [comment]
@mericsson @bradvogel as promised 😄 
https://github.com/jsforce/jsforce/pull/780

**Pull request closed without merging**
